### ISSUE TITLE
Crashes when trying to print blocks

### ISSUE THREAD

**Issue by linuzzx** [aria1th/litematica-printer#25]
Using latest version

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 07/09/2021, 11:29
Description: Unexpected error

java.lang.NoSuchMethodError: 'fi.dy.masa.litematica.util.RayTraceUtils$RayTraceWrapper fi.dy.masa.litematica.util.RayTraceUtils.getGenericTrace(net.minecraft.class_1937, net.minecraft.class_1297, double, boolean)'
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.39)
	at io.github.eatmyvenom.litematicin.utils.Printer.doPrinterAction(Printer.java:279)
	at fi.dy.masa.litematica.util.WorldUtils.doEasyPlaceAction(WorldUtils.java:1080)
	at fi.dy.masa.litematica.util.WorldUtils.handleEasyPlace(WorldUtils.java:395)
	at fi.dy.masa.litematica.event.KeyCallbacks$KeyCallbackHotkeys.onKeyAction(KeyCallbacks.java:267)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:184)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:144)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:272)
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseClick(InputEventHandler.java:181)
	at net.minecraft.client.Mouse.handler$zdp000$hookOnMouseClick(Mouse:1556)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:54)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:118)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:160)
	at net.minecraft.client.util.Window.swapBuffers(Window:442)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1137)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.eatmyvenom.litematicin.utils.Printer.doPrinterAction(Printer.java:279)
	at fi.dy.masa.litematica.util.WorldUtils.doEasyPlaceAction(WorldUtils.java:1080)
	at fi.dy.masa.litematica.util.WorldUtils.handleEasyPlace(WorldUtils.java:395)
	at fi.dy.masa.litematica.event.KeyCallbacks$KeyCallbackHotkeys.onKeyAction(KeyCallbacks.java:267)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:184)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:144)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:272)
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseClick(InputEventHandler.java:181)
	at net.minecraft.class_312.handler$zdp000$hookOnMouseClick(class_312.java:1556)
	at net.minecraft.class_312.method_1601(class_312.java:54)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)

-- Affected level --
Details:
	All players: 1 total; [class_746['GalaxyLinus'/19712, l='ClientLevel', x=1788.50, y=64.00, z=1807.66]]
	Chunk stats: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (224,68,128), Section: (at 0,4,0 in 14,4,8; chunk contains blocks 224,0,128 to 239,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 160524 game time, 38086840 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:467)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$bdk000$onCrash(class_310.java:10599)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, VanillaTweaks.zip, Better Enchantment Names (color-coded).zip, Customlang.zip, Infinity Gauntlet

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 829360280 bytes (790 MiB) / 2264924160 bytes (2160 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2,90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1f82
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 21401,90
	Virtual memory used (MB): 11877,77
	Swap memory total (MB): 5120,00
	Swap memory used (MB): 34,90
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx4096m
	Fabric Mods: 
		advancednbttooltip: Advanced NBT Tooltips 1.6.0+build.4-1.17
		afkpeace: AFKPeace 4.6.4
		amecs: Amecs 1.3.4+mc.21w16a
		amecsapi: Amecs API 1.1.4+mc21w16a
		architectury: Architectury 2.0.15
		armorhotswap: ArmorHotswap 1.4
		autoclicker-fabric: Auto Clicker 1.17.1-1.2.1-build.13
		autofish: Autofish 0.9.3
		beenfo: Beenfo 1.17.1-fabric0.36.1-1.3.2
		bettermounthud: Better Mount HUD 1.1.2
		bleachhack: BleachHack 1.0.1
		blockmeter: Block Meter ${version}
		boatiview: Boat Item View 0.0.2
		chat-up: Chat Up! 2.0
		clientcommands: Client Commands 2.5.4
		clientcommands-scripting: Clientcommands Scripting 1.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customlan: Custom LAN 1.0.0
		datareload: Data Reload 1.1
		deathlog: DeathLog 0.1.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		easiervillagertrading: EasierVillagerTrading 1.17.1-fabric0.36.1-1.5.4
		fabric: Fabric API 0.36.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d013
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea813
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446313
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57713
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa13
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446313
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446313
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31013
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57713
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446313
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c013
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa13
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57713
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446313
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612113
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446313
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e13
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463d5
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446313
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa13
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446313
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57713
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446313
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612113
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446313
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446313
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee13
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96913
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446313
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446313
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446313
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa13
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446313
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446313
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57713
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446313
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446313
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612113
		fabricloader: Fabric Loader 0.11.6
		fishelp: Fishelp 1.0.2
		gbfabrictools: GBfabrictools 1.3.4+1.17
		grass_pass: Grass Bypass 1.0.0
		held-item-info: Held Item Info 1.2.0
		horsestatsvanilla: Horse Stats Vanilla 4.1.8
		inventoryprofilesnext: Inventory Profiles Next 0.8.2
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 16
		libgui: LibGui 4.0.0-beta.4+1.17-rc1
		libninepatch: LibNinePatch 1.1.0
		lightoverlay: Light Overlay 6.0.0
		litematica: Litematica 0.0.0-dev.20210906.183617
		litematica_printer: Litematica Printer 2.3.0
		malilib: MaLiLib 0.10.0-dev.24
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 2.0.2
		monsters_in_the_closet: Monsters in the Closet 1.0.2+1.17
		multiconnect: MultiConnect 1.4.6
		multiconnect-api: MultiConnect API 1.4.6
		name_lookup: Name Lookup 1.0.1
		nostrip: No Strip 1.2.1-1.17+
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		opitems: Op Items 1.2.0
		optifabric: OptiFabric 1.11.20
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		pickblockstate: Pick-BlockState 1.0.0+1.17
		preciseblockplacing: PreciseBlockPlacing 1.7
		quickreplant: quickreplant 1.0.1
		rebind-narrator: Rebind Narrator 1.0.0
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		sectionsign: SectionSign 1.0.3
		sheepconsistency: Sheep Consistency 1.0.3
		shulkerboxtooltip: Shulker Box Tooltip 3.0.0+1.17
		shulkerdupe: Shulker dupe mod 1.0.0
		statssearch: StatsSearch 1.17-fabric0.34.9-1.0.1
		timetolive: Time To Live 0.4
		worldedit: WorldEdit 7.2.6-beta-01+1415e6f
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.11, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/VanillaTweaks.zip, file/Better Enchantment Names (color-coded).zip, file/Customlang.zip, file/Infinity Gauntlet
	Current Language: Deutsch (Deutschland)
	CPU: 12x Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	OptiFine Version: OptiFine_1.17.1_HD_U_G9
	OptiFine Build: 20210831-004129
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 471.11
	OpenGlRenderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	Suspected Mods: Litematica Printer (litematica_printer), MaLiLib (malilib), Fabric Loader (fabricloader), Litematica (litematica)

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.17.1
	OptiFine jar version: OptiFine_1.17.1_HD_U_G9
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Program Files/MultiMC/instances/Clientside Mods/.minecraft/.optifine/OptiFine_1.17.1_HD_U_G9/Optifine-mapped.jar
	OptiFabric error: <None>
```

**Comment by aria1th** [comment]
seems litematica is updated and method changed its name or something... I should look at the code, oof

**Comment by aria1th** [comment]
Updated, can you test it?

**Comment by linuzzx** [comment]
New one works for me thx

AngelBottomless ***@***.***> schrieb am Di., 7. Sept. 2021,
13:17:

**Comment by aria1th** [comment]
good
