### ISSUE TITLE
Crash 1.18.1

### ISSUE THREAD

**Issue by Jirayaboss** [aria1th/litematica-printer#50]
when i enable easy place and I do right click then it crashes showing Saving World

java.lang.NoSuchFieldError: field_21490
	at io.github.eatmyvenom.litematicin.utils.FakeAccurateBlockPlacement.request(FakeAccurateBlockPlacement.java:303)
	at io.github.eatmyvenom.litematicin.utils.Printer.doEasyPlaceFakeRotation(Printer.java:202)
	at fi.dy.masa.litematica.util.WorldUtils.handler$zkf000$onDoEasyPlaceAction(WorldUtils.java:1195)
	at fi.dy.masa.litematica.util.WorldUtils.doEasyPlaceAction(WorldUtils.java)
	at fi.dy.masa.litematica.util.WorldUtils.handleEasyPlace(WorldUtils.java:396)
	at fi.dy.masa.litematica.event.KeyCallbacks$KeyCallbackHotkeys.onKeyAction(KeyCallbacks.java:267)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:185)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:270)
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseClick(InputEventHandler.java:172)
	at net.minecraft.class_312.handler$zla000$hookOnMouseClick(class_312.java:1056)
	at net.minecraft.class_312.method_1601(class_312.java:54)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.callJV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:1061)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:196)
	at net.minecraft.class_1041.method_15998(class_1041.java:442)
	at net.minecraft.class_310.method_1523(class_310.java:1142)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by aria1th** [comment]
@Jirayaboss 
Line 303 is `if (blockState.isOf(Blocks.HOPPER) || blockState.isIn(BlockTags.SHULKER_BOXES) || blockState.isOf(Blocks.LIGHTNING_ROD) || blockState.isOf(Blocks.END_ROD)) {`
I can't find any problem with that line... 
Do you have any mods that tries to modify BlockTags, or Block Registries? 

You can try exclusive version that is being built for 1.18.1.
https://github.com/aria1th/litematica-printer/actions/runs/4560553673
