### ISSUE TITLE
not wrking properly

### ISSUE THREAD

**Issue by Jirayaboss** [aria1th/litematica-printer#52]
when placing blocks ut is not palcing to its correct orientation it does but very slowly like i have to place 1 by 1 then it works but when i hold it places randomly

bro u can chevk litematica printer

**Comment by aria1th** [comment]
@Jirayaboss Is your server paper or realm type? Those server has custom anti cheat, and it varies, so I can't support all those types. If its not, try modifying `fakeRotationTicks` settings with higher values.

**Comment by Jirayaboss** [comment]
> @Jirayaboss Is your server paper or realm type? Those server has custom anti cheat, and it varies, so I can't support all those types. If its not, try modifying `fakeRotationTicks` settings with higher values.

in 1.19.2 (old 6.8)  it is working in paper but with easyplace+ with no problem but in 1.18.2 fake rotations cant work properly with easyplace+

**Comment by aria1th** [comment]
@Jirayaboss What is your server type? I just confirmed that 7.0.1 working in vanilla / fabric server with easyPlace++, can you enable `ShowDebug~` options, and see if it says `Player facing is set to~`?

**Comment by Jirayaboss** [comment]
> @Jirayaboss What is your server type? I just confirmed that 7.0.1 working in vanilla / fabric server with easyPlace++, can you enable `ShowDebug~` options, and see if it says `Player facing is set to~`?

bro i notice 1 thing that 1.19.2 old version printer 6.8 is working ok but when i use 6.8.2 or above it is not working well if i hold right click then fake rotations stops working 

i im playing in paper earlier there was not so much problems but when you release 6.8 .2 or above fake rotations stops working when i hold right click

**Comment by aria1th** [comment]
@Jirayaboss I need debug messages to check - with `ShowDebug` options, you should see messages being printed in chat. Can you copy paste it?
I fixed packet issues in 7.0.1, so can you check with the most recent version? maybe that

**Comment by Jirayaboss** [comment]
@aria1th 
new issue
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2350.method_10166()" because "io.github.eatmyvenom.litematicin.utils.FakeAccurateBlockPlacement.fakeDirection" is null
	at net.minecraft.class_1838.handler$zmn000$onGetFacing(class_1838.java:520)
	at net.minecraft.class_1838.method_8042(class_1838.java)
	at net.minecraft.class_2510.method_9605(class_2510.java:182)
	at net.minecraft.class_1747.handler$zlh000$modifyPlacementState(class_1747.java:535)
	at net.minecraft.class_1747.method_7707(class_1747.java)
	at net.minecraft.class_1747.method_7712(class_1747.java:71)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:250)
	at net.minecraft.class_636.method_2896(class_636.java:342)
	at net.optifine.override.PlayerControllerOF.method_2896(PlayerControllerOF.java:96)
	at net.minecraft.class_310.method_1583(class_310.java:1659)
	at net.minecraft.class_310.method_1508(class_310.java:1912)
	at net.minecraft.class_310.method_1574(class_310.java:1739)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1838.handler$zmn000$onGetFacing(class_1838.java:520)
	at net.minecraft.class_1838.method_8042(class_1838.java)
	at net.minecraft.class_2510.method_9605(class_2510.java:182)
	at net.minecraft.class_1747.handler$zlh000$modifyPlacementState(class_1747.java:535)
	at net.minecraft.class_1747.method_7707(class_1747.java)
	at net.minecraft.class_1747.method_7712(class_1747.java:71)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:250)
	at net.minecraft.class_636.method_2896(class_636.java:342)
	at net.optifine.override.PlayerControllerOF.method_2896(PlayerControllerOF.java:96)
	at net.minecraft.class_310.method_1583(class_310.java:1659)
	at net.minecraft.class_310.method_1508(class_310.java:1912)

**Comment by aria1th** [comment]
@Jirayaboss I fixed it in 7.0.2!

**Comment by Jirayaboss** [comment]
> @Jirayaboss I fixed it in 7.0.2!

bro idk but suddenly it starts working idk how and that crash is fixed thanks to you
