### ISSUE TITLE
1.19.3 Enabling easy place and right clicking causes crash

### ISSUE THREAD

**Issue by Tammon23** [aria1th/litematica-printer#55]
Mods: 
fabric-api-0.73.2+1.19.3
litematica-fabric-1.19.3-0.13.0
litematica-printer-mc1.19.3-7.0.3
malilib-fabric-1.19.3-0.14.0

Crash message:

java.lang.NoSuchMethodError: 'java.util.List fi.dy.masa.litematica.schematic.placement.SchematicPlacementManager.getAllPlacementsTouchingChunk(net.minecraft.class_2338)'
	at io.github.eatmyvenom.litematicin.utils.Printer.doPrinterAction(Printer.java:368)
	at fi.dy.masa.litematica.util.WorldUtils.handler$zko000$litematica_printer$onDoEasyPlaceAction(WorldUtils.java:1228)
	at fi.dy.masa.litematica.util.WorldUtils.doEasyPlaceAction(WorldUtils.java)
	at fi.dy.masa.litematica.util.WorldUtils.handleEasyPlace(WorldUtils.java:411)
	at fi.dy.masa.litematica.event.KeyCallbacks$KeyCallbackHotkeys.onKeyAction(KeyCallbacks.java:268)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:185)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:270)
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseClick(InputEventHandler.java:172)
	at net.minecraft.class_312.handler$zlj000$malilib$hookOnMouseClick(class_312.java:1056)
	at net.minecraft.class_312.method_1601(class_312.java:54)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1222)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

Perhaps I should downgrade my litematica version? If so to which?

**Comment by Tammon23** [comment]
Seems like this is only a problem with litematica 0.13.0 so im going to close this
