### ISSUE TITLE
Game crashes when entering a world

### ISSUE THREAD

**Issue by IDontKnowWhatNameToPutHere** [aria1th/litematica-printer#78]
Version: 1.20.6
Crash report: 
```
// Daisy, daisy...

Time: 2024-06-24 11:27:11
Description: Unexpected error

java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of fi.dy.masa.litematica.render.schematic.ChunkRendererSchematicVbo failed
	at fi.dy.masa.litematica.render.schematic.WorldRendererSchematic.<init>(WorldRendererSchematic.java:83)
	at fi.dy.masa.litematica.render.LitematicaRenderer.getWorldRenderer(LitematicaRenderer.java:44)
	at fi.dy.masa.litematica.render.LitematicaRenderer.loadRenderers(LitematicaRenderer.java:52)
	at net.minecraft.class_761.handler$bdf000$litematica$onLoadRenderers(class_761.java:4186)
	at net.minecraft.class_761.method_3279(class_761.java:792)
	at net.minecraft.class_761.method_3244(class_761.java:730)
	at net.minecraft.class_310.method_18097(class_310.java:2374)
	at net.minecraft.class_310.method_1481(class_310.java:2251)
	at net.minecraft.class_634.method_11120(class_634.java:427)
	at net.minecraft.class_2678.method_11567(class_2678.java:69)
	at net.minecraft.class_2678.method_11054(class_2678.java:17)
	at net.minecraft.class_2600.method_11072(class_2600.java:25)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of fi.dy.masa.litematica.render.schematic.ChunkRendererSchematicVbo failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 22 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 26 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [litematica-printer.mixins.json:Litematica.ChunkRendererSchematicVboMixin from mod litematica_printer] from phase [DEFAULT] in config [litematica-printer.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 29 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on litematica-printer.mixins.json:Litematica.ChunkRendererSchematicVboMixin from mod litematica_printer->@Inject::onRenderBlocksAndOverlay(Lnet/minecraft/class_2338;Lfi/dy/masa/litematica/render/schematic/ChunkRenderDataSchematic;Ljava/util/Set;Ljava/util/Set;Lorg/joml/Matrix4f;Lfi/dy/masa/litematica/render/schematic/BufferBuilderCache;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lnet/minecraft/class_2338;Lfi/dy/masa/litematica/render/schematic/ChunkRenderDataSchematic;Ljava/util/Set;Ljava/util/Set;Lnet/minecraft/class_4587;Lfi/dy/masa/litematica/render/schematic/BufferBuilderCache;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/class_2338;Lfi/dy/masa/litematica/render/schematic/ChunkRenderDataSchematic;Ljava/util/Set;Ljava/util/Set;Lorg/joml/Matrix4f;Lfi/dy/masa/litematica/render/schematic/BufferBuilderCache;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> litematica-printer.mixins.json:Litematica.ChunkRendererSchematicVboMixin from mod litematica_printer -> Apply Injections ->  -> Inject -> litematica-printer.mixins.json:Litematica.ChunkRendererSchematicVboMixin from mod litematica_printer->@Inject::onRenderBlocksAndOverlay(Lnet/minecraft/class_2338;Lfi/dy/masa/litematica/render/schematic/ChunkRenderDataSchematic;Ljava/util/Set;Ljava/util/Set;Lorg/joml/Matrix4f;Lfi/dy/masa/litematica/render/schematic/BufferBuilderCache;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:564)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:494)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:277)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 29 more
```

**Comment by jamesa08** [comment]
Had this happen to me too. Looked at the mixin & it looked completely fine. Did a rebuild and it worked first try. Try this new build
[litematica-printer-mc1.20.6-7.2.0.zip](https://github.com/user-attachments/files/16104320/litematica-printer-mc1.20.6-7.2.0.zip)
